version: 1
update_configs:
  - package_manager: "javascript"
    version_requirement_updates: "increase_versions"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          dependency_name: "@tokenizer/range"
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "@tokenizer/mocha"
      - match:
          dependency_name: "ts-node"
      - match:
          dependency_name: "ts-loader"
      - match:
          dependency_name: "typescript"
      - match:
          dependency_name: "coveralls"
      - match:
          dependency_name: "@types/jasmine"
      - match:
          dependency_name: "karma"
      - match:
          dependency_name: "del-cli"
      - match:
          dependency_name: "karma-jasmine"
      - match:
          dependency_name: "karma-coverage-istanbul-reporter"
      - match:
          dependency_name: "karma-jasmine-html-reporter"
      - match:
          dependency_name: "music-metadata-browser"
      - match:
          dependency_name: "karma-firefox-launcher"
      - match:
          dependency_name: "tslint"
      - match:
          dependency_name: "webpack"
      - match:
          dependency_name: "strtok3"
      - match:
          dependency_name: "karma-jasmine"
      - match:
          dependency_name: "music-metadata"
  - package_manager: "javascript"
    version_requirement_updates: "increase_versions"
    directory: "/node"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    automerged_updates:
      - match:
          dependency_name: "@tokenizer/range"
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "@types/chai"
      - match:
          dependency_name: "@types/mocha"
      - match:
          dependency_name: "strtok3"
      - match:
          dependency_name: "ts-node"
      - match:
          dependency_name: "ts-loader"
      - match:
          dependency_name: "mocha"
      - match:
          dependency_name: "chai"
      - match:
          dependency_name: "typescript"
      - match:
          dependency_name: "coveralls"
      - match:
          dependency_name: "tslint"
      - match:
          dependency_name: "music-metadata"
      - match:
          dependency_name: "del-cli"
